#pragma once
#include "notes.h"
#define RS 13
#define ENABLE 8
#define D4 7
#define D5 1
#define D6 4
#define D7 3
#define CONTRAST_PIN 9
#define BRIGHTNESS_PIN 6
#define DIN_PIN 12
#define CLOCK_PIN 11
#define LOAD_PIN 10
#define BUZZER_PIN 5
#define PIN_SW 2
#define X_PIN A0
#define Y_PIN A1
#define PHOTORES_PIN A2
#define MATRIX_BRIGHTNESS_ADDR 44
#define CONTRAST_ADDR 40
#define BRIGHTNESS_ADDR 42
#define DIFFICULTY_ADDR 46
#define MAX_CONTR 100
#define MAX_BRIGHT 255
#define MIN_CONTR_BRIGHT 30
#define MAX_MATRX_BRIGHT 15
#define CONTR_BRIGHT_BAR_LENGTH 10
#define BAR_LENGTH 12
#define TOP_PLAYERS_SIZE 5
#define NAME_MAX_LENGTH 5
#define NOTE_SUSTAIN 20
#define LIGHT_ADJUSTMENT_DELAY 1000
#define SONG_LENGTH 26
#define  MIN_THRESHOLD 100
#define  MAX_THRESHOLD 700
#define DEBOUNCE_INTERVAL 200
#define COLUMNS 16
#define LINES 2
#define TIME_BAR_LENGTH 12
